name: Secure Flutter Web CI/CD

on:
  push:
    branches:
      - firebase_host
  pull_request:
    branches:
      - firebase_host

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"

      - name: Install dependencies
        run: flutter pub get

      - name: Run Static Code Analysis (SAST) - CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: dart  # Change to your app's language (e.g., flutter)

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

  dast-scan:
    runs-on: ubuntu-latest
    needs: build-web
    steps:
      - name: Run OWASP ZAP Dynamic Security Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "https://diamond-app-197ff.web.app/"  # Change to your Firebase hosting URL
